CREATE TABLE IF NOT EXISTS [public]."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE [public]."People" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "TenantId" text NOT NULL,
    CONSTRAINT "PK_People" PRIMARY KEY ("Id")
);

CREATE TABLE [public]."Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "TenantId" text NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

INSERT INTO [public]."People" ("Id", "Name", "TenantId")
VALUES (1, 'Person 1', 'tenant-1');
INSERT INTO [public]."People" ("Id", "Name", "TenantId")
VALUES (2, 'Person 2', 'tenant-2');
INSERT INTO [public]."People" ("Id", "Name", "TenantId")
VALUES (3, 'Person 3', 'tenant-3');

INSERT INTO [public]."Products" ("Id", "Description", "TenantId")
VALUES (1, 'Description 1', 'tenant-1');
INSERT INTO [public]."Products" ("Id", "Description", "TenantId")
VALUES (2, 'Description 2', 'tenant-2');
INSERT INTO [public]."Products" ("Id", "Description", "TenantId")
VALUES (3, 'Description 3', 'tenant-3');

SELECT setval(
    pg_get_serial_sequence('[public]."People"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM [public]."People") + 1,
        nextval(pg_get_serial_sequence('[public]."People"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('[public]."Products"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM [public]."Products") + 1,
        nextval(pg_get_serial_sequence('[public]."Products"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220316131123_Estrategia02', '6.0.3');

COMMIT;

